# Minahil Chaudhary
## Week 12 11/08/2022 - 11/10/2022

### Python Numpy Universal Functions

In [1]:
import numpy as np

In [2]:
#zip

lst1 = [1,2,3,4,5,6,7,8,9]
lst2 = [11,12,13,14,15,16,17,18,19]

z = list(zip(lst1,lst2))

z

[(1, 11),
 (2, 12),
 (3, 13),
 (4, 14),
 (5, 15),
 (6, 16),
 (7, 17),
 (8, 18),
 (9, 19)]

In [3]:
lst = []
for i,j in z:
    lst.append(i+j)
    
    
lst

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [5]:
arr_1d = np.arange(21)

In [6]:
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
#sqrt
np.sqrt(arr_1d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [8]:
np.exp(arr_1d)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [9]:
arr_1d = np.random.randn(10)
arr_1d

array([-0.00322197,  0.82102173, -1.83713046,  1.2491287 , -1.79826452,
       -1.11736018,  1.31741226, -0.50071746, -0.13323693,  0.11143744])

In [10]:
arr_1d1 = np.random.randn(10)
arr_1d1

array([ 1.01516957,  0.34795846,  0.24727521, -0.71127997,  1.03864064,
        1.31623888,  1.74756658, -1.66275853,  0.91724511, -0.22478201])

In [11]:
arr_1d + arr_1d1

array([ 1.0119476 ,  1.16898019, -1.58985525,  0.53784873, -0.75962389,
        0.1988787 ,  3.06497883, -2.16347599,  0.78400818, -0.11334458])

In [12]:
np.add(arr_1d,arr_1d1)

array([ 1.0119476 ,  1.16898019, -1.58985525,  0.53784873, -0.75962389,
        0.1988787 ,  3.06497883, -2.16347599,  0.78400818, -0.11334458])

In [14]:
arr1 = np.arange(9).reshape((3,3))
arr2 = np.ones(9).reshape((3,3))
print(arr1, '\n\n', arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
np.add(arr1, arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
arr1 < 4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [19]:
arr1 >= 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [20]:
#replace values of an array using where
np.where(arr1 < 4, 1, -1)

array([[ 1,  1,  1],
       [ 1, -1, -1],
       [-1, -1, -1]])

In [21]:
np.where((arr1 < 4) & (arr1 > 2), 1, 0)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [22]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1 * 10
arr_b = np.array([True, False, True, True, False])

print('arr1 = ', arr1, '\n\n', 'arr2= ', arr2, '\n\n', 'arr_b = ', arr_b)

arr1 =  [1 2 3 4 5] 

 arr2=  [10 20 30 40 50] 

 arr_b =  [ True False  True  True False]


In [26]:
list(zip(arr1, arr2, arr_b))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]

In [27]:
arr = [r1 if c else r2 for r1,r2,c in zip (arr1,arr2,arr_b)]
arr

[1, 20, 3, 4, 50]

In [28]:
#using np.where
arr = np.where(arr_b, arr1, arr2)
arr

array([ 1, 20,  3,  4, 50])

In [30]:
#Using where with 2 d array
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr_b = np.array([[True,False], [True,True]])
print('arr1 = ', arr1, '\n\n', 'arr2= ', arr2, '\n\n', 'arr_b = ', arr_b)

arr1 =  [[1 2]
 [3 4]] 

 arr2=  [[5 6]
 [7 8]] 

 arr_b =  [[ True False]
 [ True  True]]


In [31]:
arre = np.where(arr_b,arr1,arr2)
arr

array([ 1, 20,  3,  4, 50])

In [32]:
arr = np.where(arr_b,arr1,arr2)
arr

array([[1, 6],
       [3, 4]])

In [4]:
#any returns true if anyu of the elements of an array evaluate to true
arr_b = np.array([True,False,True,False,False])
arr_b.any()

True

In [5]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr1 > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [7]:
(arr1 >5).any()

True

In [9]:
#all () returns True if all elements evaluate to true
(arr1 > 5).all()

False

In [10]:
# unique () finds the unique elementrs of an array
fruits = np.array(['Apple', 'Cherry', 'Apple', 'Organge', 'Cherry', 'Bannana'])
fruits

array(['Apple', 'Cherry', 'Apple', 'Organge', 'Cherry', 'Bannana'],
      dtype='<U7')

In [11]:
np.unique(fruits)

array(['Apple', 'Bannana', 'Cherry', 'Organge'], dtype='<U7')

In [12]:
fruits

array(['Apple', 'Cherry', 'Apple', 'Organge', 'Cherry', 'Bannana'],
      dtype='<U7')

In [15]:
# in in1d tests whether each element of a 1 D array is also present in the second array
np.in1d(['Apple', 'Cherry', 'Grape'], fruits)

array([ True,  True, False])

In [16]:
# Descriptive Statistical Measures
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.sum()

45

In [19]:
arr.sum(0)

array([12, 15, 18])

In [20]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [21]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [22]:
np.sum(arr,axis=None)

45

In [23]:
arr.mean()

5.0

In [24]:
np.mean(arr, axis=0)

array([4., 5., 6.])

In [25]:
np.mean(arr, axis=1)

array([2., 5., 8.])

In [26]:
np.mean(arr, axis=None)

5.0

In [27]:
arr.var()

6.666666666666667

In [28]:
arr.var(0)

array([6., 6., 6.])

In [29]:
arr.var(1)

array([0.66666667, 0.66666667, 0.66666667])

In [30]:
arr.std()

2.581988897471611

In [31]:
arr.std(0)

array([2.44948974, 2.44948974, 2.44948974])

In [32]:
arr.std(1)

array([0.81649658, 0.81649658, 0.81649658])

In [33]:
arr = np.array([3,6,8,1,9,12,10,15,11,14])
arr.sort()

In [34]:
arr

array([ 1,  3,  6,  8,  9, 10, 11, 12, 14, 15])

In [35]:
arr = np.random.randn(10)
arr

array([ 0.51779964,  1.38918621,  0.6620819 , -0.12137079, -0.02324325,
        0.10054024,  0.07021342, -1.35565425,  0.66969488,  0.02842012])

In [36]:
from numpy.random import randn

In [37]:
arr = randn(3,3)
arr

array([[ 1.94557422,  1.09357904, -0.88475739],
       [ 1.32268443, -1.80092089, -1.43789642],
       [ 0.67136714, -1.74702117, -0.46510857]])

In [38]:
np.where(arr < 0, 0,1)

array([[1, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [40]:
from numpy.random import random
arr = random((4,6))
arr

array([[0.73510054, 0.84508984, 0.99843775, 0.67025652, 0.02886123,
        0.64856265],
       [0.37440448, 0.44418978, 0.68462593, 0.11424172, 0.8742284 ,
        0.53551355],
       [0.77975007, 0.47185588, 0.00523306, 0.78961923, 0.08359979,
        0.17281145],
       [0.42262802, 0.46828563, 0.28410161, 0.78618807, 0.04694694,
        0.26384347]])

In [42]:
np.random.randint(10,50)

28

In [43]:
# How to join numpy arrays by axes
# 1 D array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1, "\n\n",arr2)


[1 2 3] 

 [4 5 6]


In [44]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [45]:
np.concatenate((arr2,arr1))

array([4, 5, 6, 1, 2, 3])

In [47]:
# 2d arrays
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr1,"\n\n", arr2)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]


In [49]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
np.concatenate((arr2,arr1))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [51]:
np.concatenate((arr1,arr2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
np.concatenate((arr1,arr2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [54]:
newarr[0]

array([1, 2])

In [55]:
newarr[1]

array([3, 4])

In [56]:
newarr[2]

array([5, 6])

In [58]:
website = "http://docs.cripy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"


import webbrowser
webbrowser.open(website)

True