# Week 10 - 10/25/2022 - 11/02/2022
## Python numpy into

In [3]:
import numpy as np

In [4]:
'''
Why use NumPy?
- NumPy is a python library used for working with arrays
- Arrays are very frequently used in data science
- NumPy aims to provide an array object that is up to 50x times faster than the traditional Python lists.
- NumPy arrays are stores at one continous place in memory unlike lists
- This behavior is called locality reference in computer science
- NumPy written in C or C++
- NumPy stands for numerical Python
- The array object is NumPy is called ndarray
'''

arr = np.array([1,2,3,4,5,])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.__version__

'1.18.5'

In [7]:
print(arr)

[1 2 3 4 5]


In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
# Dimensions to arrays
#0-D Arrays
arr0d = np.array(50)
arr0d

array(50)

In [10]:
arr0d.ndim

0

In [11]:
arr0d.shape

()

In [12]:
# 1-D Array
# An array that has 0-D Arrays as its elements

In [13]:
arr1d = np.array([1,2,3,4,5,6,7])
arr1d

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
print(arr1d, arr1d.ndim, arr1d.shape)

[1 2 3 4 5 6 7] 1 (7,)


In [15]:
#2-D array - matrix
# An array that has 1-D arrays as its elements

arr2d = np.array([ [1,2,3,4,5,6] , [11, 22,33,44,55,66] ])
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [16]:
print(arr2d, arr2d.ndim, arr2d.shape)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]] 2 (2, 6)


In [17]:
arr2d.ndim

2

In [18]:
arr2d.shape

(2, 6)

In [19]:
arr2d.shape[0]

2

In [20]:
arr2d.shape[1]

6

In [21]:
#3-D array
# AN array that has 2-D arrays (matrixes) as its elements

In [22]:
arr3d = np.array([    [[1,2,3], [4,5,6]] , [[11,22,33], [44,55,66]]  ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [23]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [24]:
arr3d.shape

(2, 2, 3)

In [25]:
arr3d.ndim

3

In [26]:
# 4- D array
arr4d = np.array([1,2,3,4,5], ndmin = 4)
arr4d

array([[[[1, 2, 3, 4, 5]]]])

In [27]:
arr4d.ndim

4

In [28]:
arr4d.shape

(1, 1, 1, 5)

In [29]:
arr5d = np.array([1,2,3,4,5], ndmin = 5)
arr5d

array([[[[[1, 2, 3, 4, 5]]]]])

In [30]:
print(arr5d, arr5d.ndim, arr5d.shape)

[[[[[1 2 3 4 5]]]]] 5 (1, 1, 1, 1, 5)


In [31]:
#Array Indexing
arr1d

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
arr1d[3]

4

In [33]:
arr1d[-1]

7

In [34]:
arr1d[0] + arr1d[4]

6

In [35]:
# Access 2-D array
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [36]:
arr2d.shape

(2, 6)

In [37]:
arr2d[0]

array([1, 2, 3, 4, 5, 6])

In [38]:
arr2d[1]

array([11, 22, 33, 44, 55, 66])

In [39]:
arr2d[1, 1]

22

In [40]:
arr2d[0,5]

6

In [41]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [42]:
arr3d.shape

(2, 2, 3)

In [43]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr3d[1]

array([[11, 22, 33],
       [44, 55, 66]])

In [45]:
arr3d[1,0]

array([11, 22, 33])

In [46]:
arr3d[1][0]

array([11, 22, 33])

In [47]:
arr3d[1][0][1]

22

In [48]:
arr3d[1,0,1]

22

In [49]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [50]:
arr3d[0,1,2]

6

In [51]:
'''
slicing np arrays 
[start:end:step] step is considered 1, end index is excluded
[start:end:step]
[:end] start at index 0
[start:] end inbdex will be the length of the array

'''


arr1d

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
arr1d[1:3]

array([2, 3])

In [53]:
arr1d[:3]

array([1, 2, 3])

In [54]:
arr1d[:]

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
arr1d[::1]

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
arr1d[::2]

array([1, 3, 5, 7])

In [57]:
arr1d[::3]

array([1, 4, 7])

In [58]:
arr1d[2:]

array([3, 4, 5, 6, 7])

In [59]:
arr1d[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [60]:
arr1d[-3:-1]

array([5, 6])

In [61]:
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [62]:
arr2d.shape

(2, 6)

In [63]:
arr2d[1,3]

44

In [64]:
arr2d[0,3:]

array([4, 5, 6])

In [65]:
arr2d[1,:3]

array([11, 22, 33])

In [66]:
arr2d[0:2,3:]

array([[ 4,  5,  6],
       [44, 55, 66]])

In [67]:
arr3d.shape

(2, 2, 3)

In [68]:
arr3d[1,1,1]

55

In [71]:
arr3d[1,0,2]

33

In [72]:
arr3d[1,:,1:]

array([[22, 33],
       [55, 66]])

In [73]:
arr3d.shape

(2, 2, 3)

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [75]:
arr3d[0,:,:2]

array([[1, 2],
       [4, 5]])

In [76]:
#Differemt data elements dims for 3d
arr = np.array([   [[1,2], [4,5]], [[7,8], [10,11,3]]   ])
print(arr)

[[list([1, 2]) list([4, 5])]
 [list([7, 8]) list([10, 11, 3])]]
