# Minahil Chaudhary
## Week 11 11/01/2022
### Python Numpy - Processing Arrays

In [2]:
import numpy as np

In [3]:
arr1d = np.array([11,22,33,44,55,66])
arr1d

array([11, 22, 33, 44, 55, 66])

In [4]:
arr1d.ndim

1

In [5]:
arr1d.dtype

dtype('int32')

In [6]:
arr1d = np.array([['Orange' , 'Apple' , 'Cherry', 'Grape']])
arr1d

array([['Orange', 'Apple', 'Cherry', 'Grape']], dtype='<U6')

In [7]:
arr1d.dtype

dtype('<U6')

In [8]:
arr1d

array([['Orange', 'Apple', 'Cherry', 'Grape']], dtype='<U6')

In [9]:
d = ['Orange', 'Apple' , 'Cherry', 'Grape', 1,2,3,4,5, [6,7,8,9,10]]
arr1d = np.array(d)
arr1d

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5,
       list([6, 7, 8, 9, 10])], dtype=object)

In [10]:
arr1d.dtype

dtype('O')

In [12]:
arr1d = np.array([1,2,3,4,5,6], dtype = 'i4')
arr1d

array([1, 2, 3, 4, 5, 6])

In [13]:
arr1d.dtype

dtype('int32')

In [15]:
arr1d = np.array([1,2,3,4,5,6], dtype = 'i8')
arr1d

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [16]:
#Converting data type on existing arrays
scores = [78.5, 88.9, 90.4, 94.6]
arr1d = np.array(scores)
arr1d

array([78.5, 88.9, 90.4, 94.6])

In [18]:
arr1d.dtype

dtype('float64')

In [19]:
arr1d.astype('i')

array([78, 88, 90, 94], dtype=int32)

In [20]:
arr1d

array([78.5, 88.9, 90.4, 94.6])

In [21]:
arr1d = np.array([1,0,0,3,4,5,6,7,0])
arr1d

array([1, 0, 0, 3, 4, 5, 6, 7, 0])

In [23]:
bool_arr1d = arr1d.astype(bool)
bool_arr1d

array([ True, False, False,  True,  True,  True,  True,  True, False])

In [25]:
#NumPy array copy vs view
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

mylist = [lst1,lst2]
mylist

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [26]:
arr2d = np.array(mylist)

In [27]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [29]:
arr = arr2d

arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [30]:
arr[1,1]

22

In [31]:
arr[1,1] = 2
arr

array([[ 1,  2,  3,  4,  5],
       [11,  2, 33, 44, 55]])

In [32]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [11,  2, 33, 44, 55]])

In [33]:
arr2d[0,-1]

5

In [34]:
arr2d[0,-1] = 55

In [35]:
arr

array([[ 1,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [41]:
arr_copy = arr2d.copy()

In [42]:
arr2d

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [43]:
arr_copy

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [44]:
arr2d[0,0] = 0

In [45]:
arr

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [46]:
arr_copy

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [48]:
arr_copy # The copy is NOT be affected by the changes made to the original 

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [50]:
arr_view = arr2d.view() # View is just the view of the original array
arr_view

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [51]:
arr2d[0,0] = 100

In [52]:
arr2d

array([[100,   2,   3,   4,  55],
       [ 11,   2,  33,  44,  55]])

In [53]:
arr_view

array([[100,   2,   3,   4,  55],
       [ 11,   2,  33,  44,  55]])

In [54]:
arr_copy

array([[ 0,  2,  3,  4, 55],
       [11,  2, 33, 44, 55]])

In [55]:
arr.base

In [56]:
print(arr.base)

None


In [57]:
print(arr2d.base)

None


In [58]:
print(arr_copy.base)

None


In [59]:
print(arr_view.base)

[[100   2   3   4  55]
 [ 11   2  33  44  55]]


In [60]:
f = open("data.txt", "w")
f.write("1,2,3\n")
f.write("4,5,6\n")
f.close()

In [62]:
f = open("data.txt", "r")
print(f.read())

1,2,3
4,5,6



In [66]:
#How to import data with numpy in python
arr = np.loadtxt("data.txt", dtype = None, encoding = None, delimiter = ",")
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
arr = np.loadtxt("data.txt", dtype=None, encoding = None, delimiter= ",")
arr

array([[1., 2., 3.],
       [4., 5., 6.]])