# Minahil Chaudhary
## Week 11 - 11/3/2022
### Numpy Arrays creating, processing and transporting

In [1]:
import numpy as np

In [2]:
# Return a new array of a given shape and type, filled with zeros.
arr = np.zeros(20)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [3]:
arr.ndim

1

In [4]:
arr.dtype

dtype('float64')

In [5]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
arr.ndim

2

In [7]:
arr.shape

(5, 5)

In [8]:
arr[4]

array([0., 0., 0., 0., 0.])

In [9]:
# Return a new array of given shape and type, filled with ones. 
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr = np.ones((5,5,5))
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [11]:
arr.ndim

3

In [12]:
arr.shape

(5, 5, 5)

In [13]:
#Return a new array of given shape and type, withoutr initializing enteries

arr = np.empty((3,3))
arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.68374232e-321],
       [2.44771535e-307, 6.89796323e-307, 2.78148153e-307]])

In [14]:
arr = np.empty((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arr = np.empty((1,5))
arr

array([[0., 0., 0., 0., 0.]])

In [16]:
arr = np.empty((4,10))
arr

array([[1.69121367e-306, 6.23040373e-307, 1.02360935e-306,
        4.45061032e-308, 9.34604358e-307, 4.89542732e-307,
        1.89143671e-307, 4.67292672e-307, 1.29061821e-306,
        1.11261570e-306],
       [4.45025637e-307, 1.20161322e-306, 2.11397635e-307,
        6.23042749e-307, 8.34423068e-308, 1.11260348e-306,
        1.44635488e-307, 1.37962320e-306, 1.29060871e-306,
        1.24611266e-306],
       [3.33776697e-307, 2.78145776e-307, 3.56035923e-307,
        1.37959129e-306, 1.78021798e-306, 4.45058486e-308,
        1.24611674e-306, 6.23060065e-307, 1.89142822e-307,
        8.90071136e-308],
       [1.24610383e-306, 1.95821439e-306, 2.11392033e-307,
        1.60216183e-306, 7.56602523e-307, 1.11258446e-306,
        6.23059726e-307, 1.60218763e-306, 9.79107872e-307,
        3.56037961e-307]])

In [17]:
arr = np.empty((2,2))
arr

array([[4.68374232e-321, 2.44771535e-307],
       [6.89796323e-307, 2.78148153e-307]])

In [18]:
arr = np.empty((2,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.empty((2,4))
arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.86949987e-321, 1.00132653e-307,
        1.11261434e-306]])

In [22]:
arr = np.empty((5,3),dtype = int)
arr

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,    1316,       0],
       [      0, 4522055,       0]])

In [24]:
arr.ndim

2

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr = np.empty((2,3,2,4),dtype = int)
arr

array([[[[3801187, 5046364, 7209065, 6488169],
         [7209071, 6357092, 6619228, 7733358]],

        [[6029427, 7929968, 3604531, 6553695],
         [6684773, 7667809, 7602284, 7077980]],

        [[6422633, 7536732, 7602281, 2949221],
         [6357104, 7012451, 6750305, 7536741]]],


       [[[7209052, 7143541, 7929968, 7471196],
         [7209057, 7274596, 6029421, 7340127]],

        [[6881384, 7274604, 3014776, 7340131],
         [3604531, 7798829, 7209065, 6357087]],

        [[6553709, 3407926, 7340078, 6553721],
         [3276846, 4390958, 7209071, 6881382]]]])

In [28]:
# arrange: return evenly squared space values within a given interval
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
arr.ndim

1

In [31]:
arr = np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [32]:
# Reshapping an array
#1-D to 2D
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [37]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [38]:
#Unknown Dimenhsion -1 let numpy array figure out the number for reshapping
arr.reshape(2,-1,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr.ndim

1

In [41]:
arr.shape

(12,)

In [42]:
arr.reshape(2,6,-1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [43]:
arr.reshape(-1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [44]:
arr = np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
# Iteracting NP Arrays, iterating 1 d arrays
arr = np.arange(10)
print (arr)
for n in arr:
    print(n)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [48]:
arr2d = arr.reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
for n in arr2d:
    print(n)

[0 1 2 3 4]
[5 6 7 8 9]


In [50]:
for i in n:
    print(i)

5
6
7
8
9


In [52]:
# Iterating 3 d arrays
arr3d = np.arange(1,13).reshape(2,3,2)
arr3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [53]:
for n in arr3d:
    print (n)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [54]:
for i in n:
    print(i)

[7 8]
[ 9 10]
[11 12]


In [55]:
for x in i:
    print(x)

11
12


In [57]:
for n in arr3d:
    for i in n:
        for x in i:
            print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [58]:
#nditer itearets on each scalar element in the np array
for n in np.nditer(arr3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [59]:
#Multidimensional index iterator ndenumerate()
arr3d


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [60]:
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
for i,n in np.ndenumerate(arr2d):
    print(i,n)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


In [62]:
for i,n in np.ndenumerate(arr3d):
    print(i,n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 5
(0, 2, 1) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 1, 0) 9
(1, 1, 1) 10
(1, 2, 0) 11
(1, 2, 1) 12


In [63]:
arr3d[1,1,1]

10